#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr  9 19:49:54 2025

@author: evagnegy
"""

from netCDF4 import Dataset
import pandas as pd
import matplotlib.pyplot as plt
import warnings
import sys
import numpy as np
import datetime
import matplotlib.ticker as ticker
warnings.filterwarnings("ignore", category=DeprecationWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)
#sys.path.insert(0, '/Users/evagnegy/Desktop/CanESM2_WRF_Eval/scripts/functions/')
#from canesm2_eval_funcs import *
import WRFDomainLib
import cartopy.feature as cf
import cartopy.crs as ccrs
import matplotlib as mpl
from matplotlib import cm
import xarray as xr
import scipy
import matplotlib as mpl
import matplotlib.colors as pltcol

domain='d03'
geo_em_file = '/Users/evagnegy/Desktop/CanESM2_WRF_Eval/domain/geo_em.'+domain+'.nc'
gridded_data_path = '/Users/evagnegy/Desktop/CanESM2_WRF_Eval/gridded_model_data/daily/'


ds_mask = np.squeeze(xr.open_dataset(geo_em_file)['LANDMASK'])
ds_mask = ds_mask.rename({'south_north': 'lats', 'west_east': 'lons'})

lons = Dataset(gridded_data_path + '/t_'+domain+'_tas_daily_hist.nc','r').variables['lon'][:]
lats = Dataset(gridded_data_path + '/t_'+domain+'_tas_daily_hist.nc','r').variables['lat'][:]

lons[lons > 0] += -360


ds_lat = xr.DataArray(
    data=lats,
    coords={
        'lat': (['lats', 'lats'], lats),
        'lon': (['lons', 'lons'], lons)
    },
    dims=['lats', 'lons'],
    name='delta'
)

#%%

seas = 'djf'
event = 'cold_dry'
period = 'rcp45'

directory='/Users/evagnegy/Desktop/CanESM2_WRF_Eval/figures/compound_events/ncfiles/'


perc_hist = xr.open_dataset(f'{directory}{event}_hist_{seas}.nc')['count'].values
perc_fut = xr.open_dataset(f'{directory}{event}_{period}_base_hist_{seas}.nc')['count'].values



ds = xr.DataArray(
    data=perc_fut,
    coords={
        'lat': (['lats', 'lats'], lats),
        'lon': (['lons', 'lons'], lons)
    },
    dims=['lats', 'lons'],
    name='delta'
)


ds_masked = ds.where(ds_mask==1)


area_weights = np.cos(np.deg2rad(ds_lat))
ds_weighted = ds_masked.weighted(area_weights).mean(dim=("lats","lons"))


print(ds_weighted)





colors = ['#424c03','#41641a','#4b8c49','#79b17d','#aed0b2', '#cfe6d1','#eddaeb',
                     '#d6b4d2','#c98dc1','#ad49a0','#8c037a','#5c0250'][::-1]



cmap = pltcol.LinearSegmentedColormap.from_list("custom", colors,N=20)
cmap = cmap(np.linspace(0, 1, cmap.N))[1:-1] 
cmap = pltcol.LinearSegmentedColormap.from_list("custom", cmap,N=18)
cmap.set_over(colors[-1]) #add the max arrow color
cmap.set_under(colors[0]) #add the min arrow color
    
        
WPSFile = '/Users/evagnegy/Desktop/CanESM2_WRF_Eval/domain/namelist.wps.txt'
wpsproj, latlonproj, corner_lat_full, corner_lon_full, length_x, length_y = WRFDomainLib.calc_wps_domain_info(WPSFile)

fig1 = plt.figure(figsize=(10, 10),dpi=200)
ax1 = fig1.add_subplot(1, 1, 1, projection=wpsproj)
    
ax1.pcolormesh(lons, lats, ds_masked, cmap=cmap,vmin=-12,vmax=12, transform=ccrs.PlateCarree(),zorder=0)

ax1.set_extent([-131+1.4, -119-1.15, 46+0.4, 52-0.3], crs=ccrs.PlateCarree())

cbar_ax = fig1.add_axes([0.2, 0.09, 0.62, 0.02])
ax1.add_feature(cf.BORDERS,linewidth=0.5)
ax1.add_feature(cf.STATES,linewidth=0.5) 
fig1.colorbar(cm.ScalarMappable(cmap=cmap, norm=mpl.colors.Normalize(vmin=-60, vmax=60)),
                  cax=cbar_ax, orientation='horizontal',extend='both')#,ticks=np.arange(0, vmax+1, 0.5))
    

    







